name: Deploy to GCP DEV VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}

      - name: Sync files to remote server using rsync
        env:
          GCP_VM_USERNAME: ${{ secrets.GCP_VM_USERNAME_DEV }}
          GCP_VM_IP: ${{ secrets.GCP_VM_IP_DEV }}
        run: |
          rsync -avz --delete \
          --no-times \
          --exclude='.git/' \
          --exclude='.github/' \
          --exclude='node_modules/' \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ $GCP_VM_USERNAME@$GCP_VM_IP:/var/www/svelte-dev/
            
      - name: SSH into the server and deploy with Docker Compose
        env:
          GCP_VM_USERNAME: ${{ secrets.GCP_VM_USERNAME_DEV }}
          GCP_VM_IP: ${{ secrets.GCP_VM_IP_DEV }}
        run: |
          ssh -o StrictHostKeyChecking=no $GCP_VM_USERNAME@$GCP_VM_IP << 'EOF'
            set -e
            cd /var/www/html
            docker system prune -af
            docker compose up -d
          EOF
