name: Deploy to GCP DEV VM-testing

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"
#--------------------
# on:
#   workflow_dispatch:
#--------------------  
# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GCP_DEV_PRIVATE_KEY }}

      - name: Sync files to remote server using rsync
        env:
          GCP_DEV_USER: ${{ secrets.GCP_DEV_USER }}
          GCP_DEV_IP: ${{ secrets.GCP_DEV_IP }}
        run: |
          rsync -avz --delete \
          --no-times \
          --exclude='.git/' \
          --exclude='.github/' \
          --exclude='node_modules/' \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ $GCP_DEV_USER@$GCP_DEV_IP:/home/developer/app-engine/

      - name: SSH into the server and deploy with Docker Compose
        env:
          GCP_DEV_USER: ${{ secrets.GCP_DEV_USER }}
          GCP_DEV_IP: ${{ secrets.GCP_DEV_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no $GCP_DEV_USER@$GCP_DEV_IP << 'EOF'
            set -e
            cd /home/developer/app-engine
            docker build -t app-engine .
            
          EOF
